www.targus.com
anz.targus.com
au.targus.com
aus.targus.com
business.targus.com
cdn.targus.com
cdn.targus.com
www.cdn.targus.com
admin.targus.com
defcon.targus.com
targus.com
www.targus.com
defcon.targus.com
targus.com
www.targus.com
defcon.targus.com
dev.targus.com
dffpxg.targus.com
extranet.targus.com
www.extranet.targus.com
go.targus.com
go.targus.com
www.go.targus.com
imagedirectory.targus.com
mail.targus.com
mail.targus.com
www.mail.targus.com
a-owa.targus.com
autodiscover.private.targus.com
autodiscover.targus.com
g-owa.targus.com
legacy.targus.com
mail.targus.com
owa.targus.com
S-US01-CAS1.targus.com
S-US01-DAG1.private.targus.com
S-US01-DAG1.targus.com
S-US01-EXCH.private.targus.com
S-US02-EXCH.private.targus.com
www.mail.targus.com
autodiscover.targus.com
drmail.targus.com
mail.targus.com
owa.targus.com
S-US01-CAS1.targus.com
s-us01-exch.private.targus.com
S-US02-CAS1.targus.com
s-us02-exch1.private.targus.com
s-us02-exch2.private.targus.com
s-us02-exch.private.targus.com
s-us04-exch1.private.targus.com
www.mail.targus.com
autodiscover.targus.com
drmail.targus.com
mail.targus.com
owa.targus.com
s-us02-cas1.targus.com
s-us02-exch1.private.targus.com
s-us02-exch2.private.targus.com
s-us04-exch1.private.targus.com
www.mail.targus.com
reviews.targus.com
shop.targus.com
store.targus.com
udms.targus.com
uk.targus.com
us.targus.com
vpn06.targus.com
www.vpn06.targus.com
workspace.targus.com
de.workspace.targus.com
fr.workspace.targus.com
